"""Initial migration.

Revision ID: 2540dab46fab
Revises: 
Create Date: 2024-12-16 14:41:20.803637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2540dab46fab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('processed_images_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_progress')
    # ### end Alembic commands ###
